parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  ecmaFeatures:
    jsx: true
plugins:
  - "@typescript-eslint"
  - react
  - import
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier
  - prettier/@typescript-eslint
env:
  es6: true
  browser: true
  jest: true
  node: true
settings:
  react:
    version: detect
  import/resolver:
    alias:
      map:
        - - "@"
          - "./src"
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"
        - ".json"
        - ".d.ts"
rules:
  react/react-in-jsx-scope: off
  react/display-name: off
  react/prop-types: off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"

  import/order:
    - warn
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
