// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
// import { Document } from "@contentful/rich-text-types";

export interface IArticleFields {
  /** Title */
  title: string;

  /** Image */
  image?: Asset | undefined;

  /** slug */
  slug: string;

  /** Date */
  date?: string | undefined;

  /** Body */
  body?: string | undefined;

  /** Category */
  category?: ICategory | undefined;

  /** Tags */
  tags?: ITag[] | undefined;
}

export interface IArticle extends Entry<IArticleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "article";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICategoryFields {
  /** Name */
  name: string;

  /** Slug */
  slug: string;
}

export interface ICategory extends Entry<ICategoryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "category";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITagFields {
  /** Name */
  name: string;

  /** Slug */
  slug: string;
}

export interface ITag extends Entry<ITagFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tag";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "article" | "category" | "tag";

export type LOCALE_CODE = "ja";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "ja";
